# Generated by Django 5.0.6 on 2025-09-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='spaces',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
